[package]
name = "refinery-migrations-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
refinery = { path = "../../refinery", features = ["postgres", "tokio-postgres"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
